import { shouldUseDraftMode } from "@lib/contentful/draftMode";
import { getFooter } from "@lib/contentful/getFooter";
import { getNavigationMenu } from "@lib/contentful/getNavigationMenu";
import { getSingleEmailForm } from "@lib/contentful/getSingleEmailForm";
import { Footer } from "@src/components/shared/footer";
import { Navbar } from "@src/components/shared/navbar";
import { Toaster } from "@src/components/ui/toaster";
import { routing } from "@src/i18n/routing";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import { Outfit, Playfair_Display } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { notFound } from "next/navigation";
import "../globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});

export const metadata: Metadata = {
  title: "Iglesia de Cristo Redentor",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
  children,
  params,
}: {
  readonly children: React.ReactNode;
  readonly params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const isEnabled = await shouldUseDraftMode();
  const navMenu = await getNavigationMenu("Main menu", locale, isEnabled);
  const footerContent = await getFooter(locale, isEnabled);
  const subscribeContent = await getSingleEmailForm(
    "single-email-subscribe",
    locale,
    isEnabled,
  );

  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${outfit.variable} ${playfairDisplay.variable} font-sans antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <NextIntlClientProvider messages={messages}>
            <Navbar menuItems={navMenu} />
            {children}
            <Footer content={footerContent} subscribeContent={subscribeContent} />
            <Toaster />
          </NextIntlClientProvider>
          <SpeedInsights />
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
