#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get current branch name
branch=$(git rev-parse --abbrev-ref HEAD)

# Only run type-check and lint on main branch
if [ "$branch" = "main" ]; then
  npm run type-check && npm run lint
fi